/** 
 * Generated by erpcgen 1.13.0 on Fri Jul 19 11:28:23 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */ 


using LED.common.enums;
using io.github.embeddedrpc.erpc.auxiliary;
using System.Collections.Generic;

namespace LED.interfaces;

public interface IIO {
    void set_led(LEDName whichLed, bool onOrOff);
}



