/** 
 * Generated by erpcgen 1.13.0 on Fri Jul 19 11:28:23 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
using System.Collections.Generic;


using LED.common.enums;


namespace LED.common;

public sealed class Constants {

    private Constants() {
    }
}

