/** 
 * Generated by erpcgen 1.13.0 on Mon Jul 22 20:53:21 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */

using io.github.embeddedrpc.erpc.codec;

namespace iCNC.Servo.Connection.common.enums;

public enum Heartbeat{
    SYN = 0, 
    ACK = 1 
}