/** 
 * Generated by erpcgen 1.13.0 on Mon Jul 22 20:53:21 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */ 


using iCNC.Servo.Connection.common.enums;
using io.github.embeddedrpc.erpc.auxiliary;
using System.Collections.Generic;

namespace iCNC.Servo.Connection.interfaces;

public interface IConnection {
    void IsAlive(Heartbeat req, Reference<Heartbeat> rep);
}



