/** 
 * Generated by erpcgen 1.13.0 on Fri Jul 19 11:28:23 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */


using LED.interfaces;

using LED.common.enums;
using io.github.embeddedrpc.erpc.auxiliary;
using io.github.embeddedrpc.erpc.client;
using io.github.embeddedrpc.erpc.codec;

using System.Collections.Generic;

namespace LED.client;

public class IOClient : IIO
{
    private readonly ClientManager clientManager;
    private static readonly int SERVICE_ID = 1;
    private static readonly int SET_LED_ID = 1;

    public IOClient(ClientManager clientManager)
    {
        this.clientManager = clientManager;
    }

    public void set_led(LEDName whichLed, bool onOrOff)
    {
        // Create request
        RequestContext request = clientManager.createRequest(false);
        Codec codec = request.codec;

        // Write message info
        codec.startWriteMessage(new MessageInfo(
                MessageType.kInvocationMessage,
                SERVICE_ID,
                SET_LED_ID,
                request.sequence));

        // Write message data
        Utils.checkNotNull(whichLed, "whichLed is null");

        codec.writeInt32((int)whichLed);
        Utils.checkNotNull(onOrOff, "onOrOff is null");

        codec.writeBool(onOrOff);

        // Perform request
        foreach (var item in request.codec.array())
        {
            System.Console.WriteLine(item);
        }
        clientManager.performRequest(request);

        // Read out parameters
    }
}
