/** 
 * Generated by erpcgen 1.13.0 on Mon Jul 22 20:53:21 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
using System.Collections.Generic;


using iCNC.Servo.Connection.common.enums;


namespace iCNC.Servo.Connection.common;

public sealed class Constants {

    private Constants() {
    }
}

