/** 
 * Generated by erpcgen 1.13.0 on Thu Jul 18 14:34:12 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
using System.Collections.Generic;





namespace mat.erpc_matrix_multiply.common;

public sealed class Constants {
    /*! This const defines the matrix size. The value has to be the same as the
    Matrix array dimension. Do not forget to re-generate the erpc code once the
    matrix size is changed in the erpc file */
    public static readonly int matrix_size = 5;

    private Constants() {
    }
}

