/*
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT
 */

// Generated from ..\src\templates\dotnet_const.template
extern const char * const kDotnetConst;

const char * const kDotnetConst = 
"/** \n"
" * Generated by erpcgen {$erpcVersion} on {$todaysDate}.\n"
" * \n"
" * AUTOGENERATED - DO NOT EDIT\n"
" */\n"
"using System.Collections.Generic;\n"
"\n"
"{% if not empty(group.symbolsMap.structs) %}using {$groupPackage}.common.structs;{% elif not empty(structs)%}using {$groupPackage}.common.structs;{% endif %}\n"
"{% if not empty(enums)%}using {$groupPackage}.common.enums;{% endif %}\n"
"\n"
"{%  for inc in includes %}\n"
"using {$inc};\n"
"{%  endfor -- includes %}\n"
"\n"
"namespace {$groupPackage}.common;\n"
"\n"
"public sealed class Constants {\n"
"{% for c in consts %}\n"
"    {$>c.mlComment}\n"
"    public static readonly {$c.type.typeName} {$c.name} = {$c.value}{$getTypeValuePosfix(c.type)};{% if c.ilComment %} {$c.ilComment}{% endif %}\n"
"{% endfor %}\n"
"\n"
"    private Constants() {\n"
"    }\n"
"}\n"
"\n"
;

