/*
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT
 */

// Generated from ..\src\templates\dotnet_interface.template
extern const char * const kDotnetInterface;

const char * const kDotnetInterface = 
"{% if mlComment != \"\" %}\n"
"{$mlComment}\n"
"\n"
"{% endif %}\n"
"/** \n"
" * Generated by erpcgen {$erpcVersion} on {$todaysDate}.\n"
" * \n"
" * AUTOGENERATED - DO NOT EDIT\n"
" */ \n"
"\n"
"namespace {$groupPackage}.interfaces;\n"
"{% if not empty(group.symbolsMap.structs) %}using {$groupPackage}.common.structs;{% elif not empty(structs)%}using {$groupPackage}.common.structs;{% endif %}\n"
"{% if not empty(enums)%}using {$groupPackage}.common.enums;{% endif %}\n"
"\n"
"{%  for inc in includes %}\n"
"using {$inc};\n"
"{%  endfor -- includes %}\n"
"\n"
"using io.github.embeddedrpc.erpc.auxiliary.Reference;\n"
"\n"
"using System.Collections.Generic;\n"
"\n"
"{% if interface.mlComment %}\n"
"{$interface.mlComment}\n"
"{% else %}\n"
"{% endif %}\n"
"public interface I{$interface.name} {\n"
"    int SERVICE_ID = {$interface.id};\n"
"{% for fn in interface.functions %}\n"
"    int {$upper(fn.name)}_ID = {$fn.id};\n"
"{% endfor -- fn %}\n"
"\n"
"{% for fn in interface.functions %}\n"
"{% if fn.mlComment %}\n"
"{$fn.mlComment}\n"
"{% endif %}\n"
"    {$fn.prototype};\n"
"{% endfor -- fn %}\n"
"}\n"
"\n"
"\n"
"\n"
;

