/*
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT
 */

// Generated from ..\src\templates\dotnet_enum.template
extern const char * const kDotnetEnum;

const char * const kDotnetEnum = 
"{% if mlComment != \"\" %}\n"
"{$mlComment}\n"
"\n"
"{% endif %}\n"
"/** \n"
" * Generated by erpcgen {$erpcVersion} on {$todaysDate}.\n"
" * \n"
" * AUTOGENERATED - DO NOT EDIT\n"
" */\n"
"\n"
"namespace {$groupPackage}.common.enums;\n"
"\n"
"using io.github.embeddedrpc.erpc.codec.Codec;\n"
"\n"
"{$>(enum.mlComment or enum.ilComment)}\n"
"public enum {$enum.name}{\n"
"{%  for member in enum.members %}\n"
"{%  if member.mlComment %}\n"
"    {$member.mlComment}\n"
"{%  endif %}\n"
"    {$member.name} = {$member.value}{% if !loop.last %},{% else %}{% endif %} {% if member.ilComment %}{$member.ilComment}{% endif %}\n"
"{%  endfor -- member %}\n"
"}"
;

