/** 
 * Generated by erpcgen 1.13.0 on Fri Jul 19 11:28:23 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */

using io.github.embeddedrpc.erpc.codec;

namespace LED.common.enums;

public enum LEDName{
    kRed = 0, 
    kGreen = 1, 
    kBlue = 2 
}