/** 
 * Generated by erpcgen 1.13.0 on Thu Jul 18 14:34:12 2024.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
 

using mat.erpc_matrix_multiply.interfaces;


using io.github.embeddedrpc.erpc.auxiliary;
using io.github.embeddedrpc.erpc.client;
using io.github.embeddedrpc.erpc.codec;

using System.Collections.Generic;

namespace mat.erpc_matrix_multiply.client;

public class MatrixMultiplyServiceClient : IMatrixMultiplyService {
    private readonly ClientManager clientManager;
    private static readonly int SERVICE_ID = 1;
    private static readonly int ERPCMATRIXMULTIPLY_ID = 1;

    public MatrixMultiplyServiceClient(ClientManager clientManager) {
        this.clientManager = clientManager;
    }

    public void erpcMatrixMultiply(int[][] matrix1, int[][] matrix2, Reference<int[][]> result_matrix) {
        // Create request
        RequestContext request = clientManager.createRequest(false);
        Codec codec = request.codec;

        // Write message info
        codec.startWriteMessage(new MessageInfo(
                MessageType.kInvocationMessage,
                SERVICE_ID,
                ERPCMATRIXMULTIPLY_ID,
                request.sequence));

        // Write message data
        Utils.checkNotNull(matrix1, "matrix1 is null");
        
        for (int genLoopVariable1 = 0; genLoopVariable1 < 5; ++genLoopVariable1)
        {
            int[] genValueVariable1 = matrix1[genLoopVariable1];
            for (int genLoopVariable2 = 0; genLoopVariable2 < 5; ++genLoopVariable2)
            {
                int genValueVariable2 = genValueVariable1[genLoopVariable2];
                codec.writeInt32(genValueVariable2);
            }
        }
        Utils.checkNotNull(matrix2, "matrix2 is null");
        
        for (int genLoopVariable1 = 0; genLoopVariable1 < 5; ++genLoopVariable1)
        {
            int[] genValueVariable1 = matrix2[genLoopVariable1];
            for (int genLoopVariable2 = 0; genLoopVariable2 < 5; ++genLoopVariable2)
            {
                int genValueVariable2 = genValueVariable1[genLoopVariable2];
                codec.writeInt32(genValueVariable2);
            }
        }

        // Perform request
        clientManager.performRequest(request);

        // Read out parameters
         
        result_matrix.set(new int[5][]);
        for (int genLoopVariable1 = 0; genLoopVariable1 < 5; ++genLoopVariable1)
        {
            int[] genValueVariable1 = new int[5];
            for (int genLoopVariable2 = 0; genLoopVariable2 < 5; ++genLoopVariable2)
            {
                int genValueVariable2 = codec.readInt32();
                genValueVariable1[genLoopVariable2] = genValueVariable2;
            }
            result_matrix.get()[genLoopVariable1] = genValueVariable1;
        }
    }
}
